/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('antdv-next')['Button']
    ADrawer: typeof import('antdv-next')['Drawer']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    ASlider: typeof import('antdv-next')['Slider']
    ASpace: typeof import('antdv-next')['Space']
    ATooltip: typeof import('antdv-next')['Tooltip']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
    EntryScreen: typeof import('./components/EntryScreen.vue')['default']
    OutlinePanel: typeof import('./components/OutlinePanel.vue')['default']
    SearchBar: typeof import('./components/SearchBar.vue')['default']
    SettingsPanel: typeof import('./components/SettingsPanel.vue')['default']
    StatusBar: typeof import('./components/StatusBar.vue')['default']
  }
}
